# Site settings
title: 陈松的技术博客
SEOTitle: 陈松的技术博客 | CS Blog
header-img: img/post-bg-desk.jpg
email: chensongbj25@gmail.com
description: "Every failure is leading towards success."
keyword: "陈松的技术博客, 陈松C/C++ blog, 高并发, 高可用的服务器"
url: "https://chensongpoixs.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/chensongpoixs/chensongpoixs.github.io.git" # you code repository

plugins:
  - jekyll-sitemap

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "每天进步一点点 对技术有追求的小白."
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     chensongpoixs
#zhihu_username:     chensongpoixs
csdn_username:		Poisx
github_username:    chensongpoixs
#facebook_username:  chensongpoixs
jianshu_username:   c5bcb0434259
#twitter_username:   chensongpoixs
email_account:      chensongbj25@gmail.com



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

      
duoshuo_share: true  

# 评论系统
# Disqus（https://disqus.com/）
disqus_username: chensongpoixs-github-io-1


# Gitalk
gitalk:
enable: true    #是否开启Gitalk评论
   clientID: 68eab7a4e477a095f0fe                            #生成的clientID
   clientSecret: 2d99a84787d60946674b419700c43dda76e6d121    #生成的clientSecret
   repo: chensongpoixs.github.io    #仓库名称
   owner: chensongpoixs    #github用户名
   admin: chensongpoixs
   distractionFreeMode: true #是否启用类似FB的阴影遮罩
#
# 统计

# Analytics settings
#Baidu Analytics
#ba_track_id: 11ea1e5954a4193d6dc9aa404767aa89

#用户名 -- 15850774503-> two
ba_track_id: e4d3c801e2dcc7346b7cc4e86ad11344


# Google Analytics
ga_track_id: 'UA-131362317-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/Poisx"
    },{
        title: "简·书",
        href: "http://www.jianshu.com/u/c5bcb0434259"
    },{ 
        title: "GitHub",
        href: "https://github.com/chensongpoixs"
	}
]
